from . import common_dates
from . import common_projects
from . import common_requirements
from . import crm_lead
from . import hr_job
from . import project
from . import project_abstract_requirement_line
from . import project_abstract_subrequirement_line
from . import project_custom_requirement_line
from . import project_custom_subrequirement_line
from . import project_department
from . import project_department_lot
from . import project_profile_line
from . import project_requirement
from . import project_requirement_line
from . import project_subrequirement
from . import project_subrequirement_line
from . import project_task
